spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basicecommerce?createDatabaseIfNotExist=true
    username: root
    password: Awesomeness123
  jpa:
    show-sql: true

websiteUrl: http://localhost:4242